image: golang:1.9

variables:
  CUSTOM_UI_DIR: 'jenkins/sc-plugin/CustomUI'
  DEVSPACE_W: '//backup01/devspace'
  DEVSPACE_L: '/mnt/devspace'
  PLUGIN_NAME_LIST: 'BlitzScPlugin FedresursDSPlugin BrowserDSPlugin'
  DISTR_STORE_PATH: 'sc-plugin/build'
  BUILD_TYPE: 'Release'
  MAC_OS_SIGN_CERT_CN: "Developer ID Installer: REAK SOFT, OOO \\(Y2B5234KDQ\\)"
  SIGN_FILE_DIR: 'C:/gitlab/reaxoft-sign-certificates'
  BUILD_PARAM_FILE: 'build_params.sh'
  GOPATH: /home/gitlab-runner/go
  REPO_NAME: git.reaxoft.ru/infomir/custodian

## test

stages:
  - build

build:
  stage: build
  tags:
    - master
  only:
    - master
    - /^release-\d.\d.\d.\d$/
  script:
    - set -x;
    - mkdir -p $CI_PROJECT_DIR/artifacts;
    - rm -rf $GOPATH/src/$REPO_NAME && mkdir -p $GOPATH/src/$REPO_NAME;
    - mv $CI_PROJECT_DIR/* $GOPATH/src/$REPO_NAME/;
    - cd $GOPATH/src/$REPO_NAME;
    - go build -o $CI_PROJECT_DIR/artifacts/custodian;
    - set +x;
  artifacts:
    paths:
      - artifacts/custodian
