version: "2"

services:

  generics_custodian:
    extends:
      file: ./custodian/deployment/docker-compose.yml
      service: custodian
    container_name: generics.custodian.experiments
    environment:
      SERVICE_DOMAIN: "CUSTODIAN"
      SERVICE_AUTH_SECRET: "56ba7790bd83484d9edbc13206775e22a38f064bf564ee0546d65c86c62b937eb3b3d9508fdaf445c6842bc2630902bdbb1d5801d0db531b45da8abf14c99b18"
      DB_SETTINGS: "host=postgres.generics.custodian.experiments user=custodian password=custodian dbname=custodian sslmode=disable"
      AUTH_URL: "http://authorization.trood:8000"
    ports:
      - "8000"
    networks:
      - trood_main-network

  generics_custodian_postgres:
    extends:
      file: ./custodian/deployment/docker-compose.yml
      service: custodian_postgres
    container_name: postgres.generics.custodian.experiments
    networks:
      - trood_main-network

networks:
  trood_main-network:
    external: true
  test-network:
    driver: bridge