FROM golang:1.10

WORKDIR /go/src

COPY ./src/logger /go/src/logger
COPY ./src/server /go/src/server
COPY ./src/utils /go/src/utils
COPY ./deployment/wait-for-it.sh /go/src
COPY ./deployment/run-tests.sh /go/src
COPY ./main.go /go/src/

RUN go get -d -v
RUN go get github.com/onsi/ginkgo/ginkgo
RUN go get github.com/onsi/gomega/...

RUN chmod +x /go/src/run-tests.sh
RUN chmod +x /go/src/wait-for-it.sh
CMD ["tail", "-f", "/dev/null"]