version: "2"

services:
  custodian:
    image: registry.getbino.com/${COMPOSE_PROJECT_NAME}/custodian:latest
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    container_name: custodian
    networks:
      - test-network

  custodian_postgres:
    image: postgres:9.5
    container_name: postgres.custodian
    volumes:
      - ./postgres/${DB_NAME}/data:/var/lib/postgresql/data
      - ./postgres/${DB_NAME}/conf:/etc/postgresql
      - ./postgres/${DB_NAME}/logs:/var/log/postgresql
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: custodian
      POSTGRES_USER: custodian
      POSTGRES_PASSWORD: custodian

    networks:
      - test-network

networks:
  test-network:
    driver: bridge