version: "2.2"

services:
  custodian:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    container_name: custodian
    environment:
      DATABASE_URL: "pgsql://custodian:custodian@postgres.custodian/custodian?sslmode=disable"
    networks:
      - test-network

  custodian_postgres:
    image: postgres:12
    container_name: postgres.custodian
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: custodian
      POSTGRES_USER: custodian
      POSTGRES_PASSWORD: custodian
    networks:
      - test-network

networks:
  test-network:
    driver: bridge