version: "2"

services:
  custodian:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile-tests
    container_name: custodian
    environment:
      DB_CONNECTION_OPTIONS: "user=custodian password=custodian host=postgres.custodian port=5432 dbname=custodian sslmode=disable"

  custodian_postgres:
    image: postgres:10.5
    container_name: postgres.custodian
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: custodian
      POSTGRES_USER: custodian
      POSTGRES_PASSWORD: custodian
