version: "2"

services:
  custodian:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
    env_file: ../.env
    container_name: custodian
    networks:
      - test-network

  custodian_postgres:
    image: postgres:9.6
    container_name: postgres.custodian
    entrypoint: "docker-entrypoint.sh postgres -c \"idle_in_transaction_session_timeout=10000\""
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: custodian
      POSTGRES_USER: custodian
      POSTGRES_PASSWORD: custodian

    networks:
      - test-network

networks:
  test-network:
    driver: bridge