version: "2"

services:
  custodian:
    build:
      context: ../
      dockerfile: ./deployment/Dockerfile
      args:
        DB_HOST: "postgres.custodian"
        DB_USER: "custodian"
        DB_PASSWORD: "custodian"
        DB_PORT: "5432"
        DB_NAME: "custodian"
        DB_SSL_MODE: "disable"
    container_name: custodian

  custodian_postgres:
    image: postgres:10.5
    container_name: postgres.custodian
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: custodian
      POSTGRES_USER: custodian
      POSTGRES_PASSWORD: custodian